### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by farishkash** [testmysk1ll/Colmar-academy#1]
https://github.com/testmysk1ll/Colmar-academy/blob/04d4aae0afbceed00ac299faab3b652612b6d9b8/Documents/projects/Colmar_Academy/capstone_colmar_assets/css/style.css#L88

You only want to write the media query for each size once and at the bottom after all your non-media query CSS.

There are a couple reasons for this.

First, when you write multiple of the same device

` @media only screen and (max-width: 760px) { `

If the CSS is broken in an earlier one, it can break the rest of your CSS in your other media queries.  This can make it much more difficult to find.

Second, when you write this once and at the bottom of your CSS file, you create a clear distinctive starting point for all your media query CSS.  There are many times where I have seen learners write desktop CSS in their media query and vice versa.  This helps avoid potential confusion and errors.

The screenshot below is from the middle of your CSS file.  Is this part of a media query or not?  The answer doesn't matter, but if your media queries at the end of your CSS then this question never has to be answered.  That is what I am trying to prevent by mentioning this organizational practice.

![colmar-academy_style_css_at_master_ _testmysk1ll_colmar-academy](https://user-images.githubusercontent.com/5844161/36998714-bc01629a-2072-11e8-9db3-f36b783817bf.png)

**Comment by testmysk1ll** [comment]
many thanks, this is very helpful.
