### ISSUE TITLE
Mobile View is slightly off center

### ISSUE THREAD

**Issue by farishkash** [testmysk1ll/Colmar-academy#2]
![colmar_academy1](https://user-images.githubusercontent.com/5844161/36998848-303b2b96-2073-11e8-874d-9f782c950fdf.png)

You have padding pushback in some of the inner divs.  It will most likely go to the center by removing these and reducing width size of the div.  On mobile devices sometimes making the box 95 percent or less of the width gives you a comparable effect and will automatically adjust to the size of the screen.

**Comment by testmysk1ll** [comment]
many thanks, this is very helpful.
