### ISSUE TITLE
Consider meaningful class names.

### ISSUE THREAD

**Issue by farishkash** [testmysk1ll/Colmar-academy#3]
Class names convey better when they are related to the content.

Some examples
<div class="TopMain">  <--- could be intro

<div class="MiddleMain"><--- courses
<div class="DESlongcontainer">  I believe you mean description, course_description, 

Comments and meaningful class names become documentation for your website.  If you are given a project and you haven't touch it for a couple years, this helps you go back visualize what you had been working on.

**Comment by testmysk1ll** [comment]
many thanks, this is very helpful.
